### ISSUE TITLE
Fail with "TypeError: Cannot read property 'bold' of undefined"

### ISSUE THREAD

**Issue by AndreasPresthammer** [asbjornenge/generator-microlib#4]
Created new directory
Ran `yo microlib`

Got the following error:
`TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (C:\Users\aha\AppData\Roaming\npm\node_modules\generator-microlib\node_modules\yeoman-generator\lib\util\common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\aha\AppData\Roaming\npm\node_modules\generator-microlib\node_modules\yeoman-generator\lib\base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

Ran under Windows and powershell.

No output in the directory.

I ran `yo webapp` with the generator-webapp plugin, and that seemed to work fine.

**Comment by asbjornenge** [comment]
Alright, thanks! Seems to be something in the underlying yeoman-generator code. I'll look into upgrading.

**Comment by asbjornenge** [comment]
Alright, give 0.2.1 :package: a try. Sorry i took me a few days. If you keep having issues try

```
npm cache clean
```

and perhaps upgrading yeoman-generator & yo (if you have them globally installed).
